-- =================================================================================
-- V6: CHUYỂN ĐỔI ID SANG IDENTITY VÀ TẮT CACHE ĐỂ ĐẢM BẢO SỐ THỨ TỰ TĂNG TUẦN TỰ
-- =================================================================================

-- 1. Xóa liên kết DEFAULT cũ của BIGSERIAL (V1 đã tạo)
-- Lệnh này giúp tách cột ID ra khỏi hệ thống sequence cũ của SERIAL
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;

-- 2. Chuyển đổi cột ID sang chuẩn GENERATED BY DEFAULT AS IDENTITY
-- START WITH 1: Giá trị khởi tạo
-- CACHE 1: Quan trọng nhất - Ép Postgres không lưu tạm ID vào RAM, đảm bảo tăng 1, 2, 3...
ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1 CACHE 1);

-- 3. Đồng bộ lại giá trị Sequence hiện tại
-- Giúp tránh lỗi "Unique Constraint" nếu bảng đã có dữ liệu từ các lần đăng ký trước
SELECT setval(pg_get_serial_sequence('users', 'id'), coalesce(max(id), 1)) FROM users;

-- 4. Củng cố hàm Trigger cập nhật thời gian (Đảm bảo tính đồng nhất)
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';