-- =================================================================================
-- V6: CHUYỂN ĐỔI ID SANG IDENTITY VÀ TẮT CACHE ĐỂ ĐẢM BẢO SỐ THỨ TỰ TĂNG TUẦN TỰ
-- =================================================================================

-- 1. Xóa liên kết DEFAULT cũ của BIGSERIAL (V1 đã tạo)
-- Lệnh này giúp tách cột ID ra khỏi sequence tự động cũ
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;

-- 2. Chuyển đổi cột ID sang chuẩn GENERATED BY DEFAULT AS IDENTITY
-- START WITH: Bắt đầu từ 1 (Flyway sẽ tự sync lại giá trị max ở bước 3)
-- CACHE 1: Quan trọng nhất - Ép Postgres không lưu tạm ID vào RAM, đảm bảo 1, 2, 3...
ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1 CACHE 1);

-- 3. Đồng bộ lại giá trị Sequence hiện tại
-- Giúp tránh lỗi "Unique Constraint" nếu bảng đã có dữ liệu từ trước
SELECT setval(pg_get_serial_sequence('users', 'id'), coalesce(max(id), 1));

-- 4. Cập nhật lại hàm Trigger (Nếu bạn có thay đổi logic cập nhật thời gian)
-- Bước này mang tính củng cố, đảm bảo hàm luôn tồn tại và chính xác
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';